/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DruggistRole;

import Business.Enterprises.Enterprise;
import Business.Network.NetworkSystem;
import Business.UserAccount.User_Account;
import Business.WorkStream.DrugDistributorWorkRequest;
import Business.WorkStream.FundsWorkRequest;
import Business.WorkStream.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Makarand
 */
public class DruggistInventoryJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    private Enterprise enterprise;
    private User_Account userAccount;
    private NetworkSystem network;

    /**
     * Creates new form PharmacistInventoryInfoJPanel
     */
    public DruggistInventoryJPanel(JPanel userProcessContainer, NetworkSystem network, Enterprise enterprise, User_Account account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        populateDrugDistributorRequestData();
        populateInventory();
        
    }
    
    public void populateDrugDistributorRequestData(){
        DefaultTableModel model = (DefaultTableModel) drugDistributorRequestsTbl.getModel();
        model.setRowCount(0);
        
        for (WorkRequest request : userAccount.getWorkStream().getWorkRequestList()) {
            if(request instanceof DrugDistributorWorkRequest){
                Object[] row = new Object[4];
                row[0] = request;
                row[1] = request.getSender().getUsername();
                row[2] = request.getReceiver() == null? "" :request.getReceiver().getUsername();
                String result = request.getStatus();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        requestSuppllierBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        acaTxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        antTxt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        camTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        disTxt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vivTxt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugDistributorRequestsTbl = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 241, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back_button.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 14, -1, 55));

        requestSuppllierBtn.setBackground(new java.awt.Color(239, 241, 228));
        requestSuppllierBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        requestSuppllierBtn.setText("Request Distributor ");
        requestSuppllierBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        requestSuppllierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestSuppllierBtnActionPerformed(evt);
            }
        });
        jPanel1.add(requestSuppllierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 176, 50));

        jButton3.setBackground(new java.awt.Color(239, 241, 228));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton3.setText("Accept Medicine Request");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 176, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pills_icon.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 1080));

        jPanel6.setBackground(new java.awt.Color(193, 212, 227));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Checking for Patient <name>");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(475, 475, 475)
                .addComponent(jLabel1)
                .addContainerGap(963, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 0, 1700, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(239, 241, 228));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Required Medicines are: ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 225, 50));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Drug List");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 141, 35));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Count");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 141, 35));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Acamprosate");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 141, 35));

        acaTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        acaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(acaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 141, 35));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Antabuse");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 141, 35));

        antTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        antTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(antTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 141, 35));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Campral");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 141, 35));

        camTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        camTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(camTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 141, 35));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Disulfiram");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 141, 35));

        disTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        disTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(disTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 141, 35));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Vivitrol");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 141, 35));

        vivTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        vivTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(vivTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 141, 35));

        drugDistributorRequestsTbl.setBackground(new java.awt.Color(0, 0, 0));
        drugDistributorRequestsTbl.setForeground(new java.awt.Color(255, 255, 255));
        drugDistributorRequestsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Reciever", "Status"
            }
        ));
        drugDistributorRequestsTbl.setShowGrid(true);
        jScrollPane2.setViewportView(drugDistributorRequestsTbl);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 630, 210));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 650, 620));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/drug.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1970, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 1650, 990));
    }// </editor-fold>//GEN-END:initComponents

    public void populateInventory(){
        acaTxt.setText(Integer.toString(userAccount.getDruggistInventory().getCountAcamprosate()));
        vivTxt.setText(Integer.toString(userAccount.getDruggistInventory().getCountVivitrol()));
        disTxt.setText(Integer.toString(userAccount.getDruggistInventory().getCountDisulfiram()));
        camTxt.setText(Integer.toString(userAccount.getDruggistInventory().getCountCampral()));
        antTxt.setText(Integer.toString(userAccount.getDruggistInventory().getCountAntabuse()));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        
        DruggistWorkAreaJPanel dwajp = (DruggistWorkAreaJPanel) component;
        dwajp.populateMedData();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRow = drugDistributorRequestsTbl.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        
        DrugDistributorWorkRequest request = (DrugDistributorWorkRequest)drugDistributorRequestsTbl.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Drugs Sent")){
            JOptionPane.showMessageDialog(null, "Drugs Consignment Accepted! Check inventory");
            userAccount.getDruggistInventory().setCountAcamprosate(request.getCountAcamprosate());
            userAccount.getDruggistInventory().setCountAntabuse(request.getCountAntabuse());
            userAccount.getDruggistInventory().setCountCampral(request.getCountCampral());
            userAccount.getDruggistInventory().setCountDisulfiram(request.getCountDisulfiram());
            userAccount.getDruggistInventory().setCountVivitrol(request.getCountVivitrol());
            request.setStatus("Completed");
            populateInventory();
        }
        else{
            JOptionPane.showMessageDialog(null, "Drugs Not received yet");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void requestSuppllierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestSuppllierBtnActionPerformed
        RequestSupplierJPanel requestSupplierJPanel = new RequestSupplierJPanel(userProcessContainer,network,userAccount,enterprise);
        userProcessContainer.add("Request", requestSupplierJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestSuppllierBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acaTxt;
    private javax.swing.JLabel antTxt;
    private javax.swing.JLabel camTxt;
    private javax.swing.JLabel disTxt;
    private javax.swing.JTable drugDistributorRequestsTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton requestSuppllierBtn;
    private javax.swing.JLabel vivTxt;
    // End of variables declaration//GEN-END:variables
}
