/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PharmacotherapistDocRole;

import Business.Enterprises.Enterprise;
import Business.Network.NetworkSystem;
import Business.Organization.PharmacotherapistOrg;
import Business.UserAccount.User_Account;
import Business.WorkStream.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pranali
 */
public class treatJPanel extends javax.swing.JPanel {

    /**
     * Creates new form treatJPanel
     */
   

    JPanel userProcessContainer;
    User_Account userAccount;
    PharmacotherapistOrg organization;
    Enterprise enterprise;
    NetworkSystem network; 
    WorkRequest request;
    String treatment_methods[] = {"Trauma-Informed Therapy", "Diet, Nutrition , & Wellness Therapy", "Group Therapy", "Individual Therapy","Come for Cognitive Behavioral Therapy"};

    treatJPanel(JPanel userProcessContainer, User_Account userAccount, PharmacotherapistOrg organization, Enterprise enterprise, NetworkSystem network, WorkRequest request) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.userAccount = userAccount;
    this.organization = organization;
    this.enterprise = enterprise;
    this.network = network;
    this.request = request;
    Loadddl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ddlmeetings = new javax.swing.JComboBox();
        btnsenddecision = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(239, 241, 228));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel1.setText("Select meeting frequency");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        ddlmeetings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlmeetingsActionPerformed(evt);
            }
        });
        jPanel3.add(ddlmeetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 360, 210, 40));

        btnsenddecision.setBackground(new java.awt.Color(239, 241, 228));
        btnsenddecision.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnsenddecision.setText("Send Decision to patient");
        btnsenddecision.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnsenddecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsenddecisionActionPerformed(evt);
            }
        });
        jPanel3.add(btnsenddecision, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 170, 60));

        backJButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back_button.png"))); // NOI18N
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pharma_logo.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 90, 100));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 266, 869));

        jPanel6.setBackground(new java.awt.Color(193, 212, 227));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel7.setText("Pharmacotherapist Work Area");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 50));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 0, 1200, 80));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pharma2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 960, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void btnsenddecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsenddecisionActionPerformed
     request.setDiagnose( (String )ddlmeetings.getSelectedItem() + " is recommended by  Phrmacotherapist" );
     JOptionPane.showMessageDialog(null, "Decision sent to patient ");
    }//GEN-LAST:event_btnsenddecisionActionPerformed

    private void ddlmeetingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlmeetingsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ddlmeetingsActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PharmacotherapistWorkAreaJPanel pcwjp= (PharmacotherapistWorkAreaJPanel) component;
//        pcwjp.populatePharmadata();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton btnsenddecision;
    private javax.swing.JComboBox ddlmeetings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    private void Loadddl() {
        for(String str: treatment_methods)
       {
           ddlmeetings.addItem(str);
       }
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
