/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DoctorRole;

import Business.Enterprises.Enterprise;
import Business.Network.NetworkSystem;
import Business.Organization.DoctorConsultantOrg;
import Business.Organization.Org;
import Business.UserAccount.User_Account;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Makarand
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorConsultantOrg organization;
    private Enterprise enterprise;
    private User_Account userAccount;
    private NetworkSystem network;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, User_Account account,
            Org organization, Enterprise enterprise, NetworkSystem network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (DoctorConsultantOrg) organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medcampreqbtn = new javax.swing.JButton();
        btnViewStatistics = new javax.swing.JButton();
        viewaptreqbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1170, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medcampreqbtn.setBackground(new java.awt.Color(83, 124, 142));
        medcampreqbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        medcampreqbtn.setForeground(new java.awt.Color(255, 255, 255));
        medcampreqbtn.setText("View Medical Camp request");
        medcampreqbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medcampreqbtnActionPerformed(evt);
            }
        });
        add(medcampreqbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 287, 50));

        btnViewStatistics.setBackground(new java.awt.Color(83, 124, 142));
        btnViewStatistics.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnViewStatistics.setForeground(new java.awt.Color(255, 255, 255));
        btnViewStatistics.setText("View Statistics");
        btnViewStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStatisticsActionPerformed(evt);
            }
        });
        add(btnViewStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 444, 287, 50));

        viewaptreqbtn.setBackground(new java.awt.Color(249, 248, 248));
        viewaptreqbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        viewaptreqbtn.setText("View Appointment Requests");
        viewaptreqbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewaptreqbtnActionPerformed(evt);
            }
        });
        add(viewaptreqbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 354, 287, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/doctor_backnew.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

     //   System.out.println("assign to me pressed ");


    }//GEN-LAST:event_assignJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
    //     System.out.println("refresh pressed ");
        //populateRequestTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

     

    private void medcampreqbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medcampreqbtnActionPerformed
        // TODO add your handling code here:
        DoctorMedicalCampRequestJPanel doctorMedicalJPanel = new DoctorMedicalCampRequestJPanel(userProcessContainer, userAccount, organization, enterprise);
        userProcessContainer.add("DoctorMedicalCampRequestJPanel", doctorMedicalJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_medcampreqbtnActionPerformed

    private void btnViewStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStatisticsActionPerformed
        StatisticsJPanel statisticsJPanel = new StatisticsJPanel(userProcessContainer, userAccount, organization, enterprise, network);
        userProcessContainer.add("statisticsJPanel", statisticsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewStatisticsActionPerformed

    private void viewaptreqbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewaptreqbtnActionPerformed
        DoctorAppointmentRequestsJPanel doctorAppointmentReq = new DoctorAppointmentRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, network);
        userProcessContainer.add("DoctorAppointmentJPanel", doctorAppointmentReq);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewaptreqbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewStatistics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton medcampreqbtn;
    private javax.swing.JButton viewaptreqbtn;
    // End of variables declaration//GEN-END:variables
}
