/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CSRManagerRole;

import Business.Ecosystem.Ecosystem;
import Business.Enterprises.Enterprise;
import Business.Organization.CSROrganization;
import Business.UserAccount.User_Account;
import Business.WorkStream.MedicalCampWorkRequest;
import Business.WorkStream.NgoMedCampWorkRequest;
import Business.WorkStream.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pranali
 */
public class CSRManagerWorkAreajPanel extends javax.swing.JPanel {

    /**
     * Creates new form CSRManagerWorkAreajPanel
     */
    private JPanel userProcessContainer;
    private CSROrganization organization;
    private Enterprise enterprise;
    private User_Account userAccount;
    private Ecosystem business;
    public CSRManagerWorkAreajPanel(JPanel userProcessContainer, User_Account account, CSROrganization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        populateRequestTable();
    }
 public void populateRequestTable(){
        DefaultTableModel model1 = (DefaultTableModel) ReqFromNGOMedicalCamp.getModel();
        
        model1.setRowCount(0);
        for (WorkRequest request : organization.getWorkStream().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getSender();
            row[2] = request.getReceiver();
            row[3] = request.getStatus();
            String result = ((MedicalCampWorkRequest) request).getCampResult();
            row[4] = result == null ? "Waiting" : result;
            
            model1.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReqFromNGOMedicalCamp = new javax.swing.JTable();
        refreshTestJButton = new javax.swing.JButton();
        assignBtn = new javax.swing.JButton();
        reqNgoBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 241, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CSR Work Area Panel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(193, 212, 227));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReqFromNGOMedicalCamp.setBackground(new java.awt.Color(0, 0, 0));
        ReqFromNGOMedicalCamp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ReqFromNGOMedicalCamp.setForeground(new java.awt.Color(255, 255, 255));
        ReqFromNGOMedicalCamp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Assigned To", "Status", "Camp result"
            }
        ));
        ReqFromNGOMedicalCamp.setShowGrid(true);
        jScrollPane2.setViewportView(ReqFromNGOMedicalCamp);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 519, 260));

        refreshTestJButton.setBackground(new java.awt.Color(83, 124, 142));
        refreshTestJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 175, 50));

        assignBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        assignBtn.setText("Assign to me");
        assignBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        jPanel2.add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 140, 50));

        reqNgoBtn.setBackground(new java.awt.Color(83, 124, 142));
        reqNgoBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reqNgoBtn.setText("Request ");
        reqNgoBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reqNgoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqNgoBtnActionPerformed(evt);
            }
        });
        jPanel2.add(reqNgoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 141, 50));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 580, 360));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/csr_backnew.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1220, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void reqNgoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqNgoBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = ReqFromNGOMedicalCamp.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        
        MedicalCampWorkRequest medcampWReq= (MedicalCampWorkRequest)ReqFromNGOMedicalCamp.getValueAt(selectedRow, 0);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("Process CSR requests", new RequestDoctorForMedCampJPanel(userProcessContainer, userAccount, enterprise,medcampWReq));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reqNgoBtnActionPerformed

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = ReqFromNGOMedicalCamp.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        MedicalCampWorkRequest medcampWReq = (MedicalCampWorkRequest)ReqFromNGOMedicalCamp.getValueAt(selectedRow, 0);
        if(medcampWReq.getReceiver() == null){
            medcampWReq.setReceiver(userAccount);
            medcampWReq.setStatus("Pending from CSR");
            populateRequestTable();
        }
        else{
            JOptionPane.showMessageDialog(null, "Already Assigned");
            return;
        }
    }//GEN-LAST:event_assignBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ReqFromNGOMedicalCamp;
    private javax.swing.JButton assignBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton reqNgoBtn;
    // End of variables declaration//GEN-END:variables
}
