/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.FundsProviderRole;

import Business.WorkStream.FundsWorkRequest;
import Business.WorkStream.FundsWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pranali
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    JPanel userProcessContainer;
    FundsWorkRequest request;
    boolean emptyValidationStatus = true;
    boolean validationCheck = true;
    ProcessWorkRequestJPanel(JPanel userProcessContainer, FundsWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        amountTxtField = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 241, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back_button.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 70, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Process WorkRequest");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(193, 212, 227));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Result");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 69, -1));

        resultJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(resultJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 201, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Amount");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 26));

        amountTxtField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTxtFieldActionPerformed(evt);
            }
        });
        jPanel2.add(amountTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 201, -1));

        submitJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 550, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fund1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1240, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        try{
            if(EmpytyFieldValidation()){
                
                    request.setTestResult(resultJTextField.getText());
                    request.setAmountFunded(Integer.parseInt(amountTxtField.getText()));
                    request.setStatus("Completed");
                    resultJTextField.setText("");
                    amountTxtField.setText("");
                
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Result not submitted, Try again");
            System.out.println(e.toString());
            emptyValidationStatus=true;
        }
        
//        request.setTestResult(resultJTextField.getText());
//        request.setAmountFunded(Integer.parseInt(amountTxtField.getText()));
//        request.setStatus("Completed");
//        resultJTextField.setText("");
//        amountTxtField.setText("");
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FundsProviderWorkAreaJPanel fpwajp = (FundsProviderWorkAreaJPanel) component;
        fpwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void amountTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTxtFieldActionPerformed

//    private boolean RegexValidation() {
//        if(!amountTxtField.getText().matches("^[0-9]{15}$"))
//        {
//            amountTxtField.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
//            amountTxtField.setToolTipText("Please enter a valid amount");
//            validationCheck=false;
//        }
//        
//        if(amountTxtField.getText().matches("^[0-9]{15}$"))
//        {
//            amountTxtField.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
//        }
//        return validationCheck;
//    }
    
    private boolean EmpytyFieldValidation() {
        if(resultJTextField.getText().equals(null) || resultJTextField.getText().trim().isEmpty() )
        {
            resultJTextField.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            resultJTextField.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!resultJTextField.getText().equals(null) && !resultJTextField.getText().trim().isEmpty() )
        {
            resultJTextField.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }
        if(amountTxtField.getText().equals(null) || amountTxtField.getText().trim().isEmpty() )
        {
            amountTxtField.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            amountTxtField.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!amountTxtField.getText().equals(null) && !amountTxtField.getText().trim().isEmpty() )
        {
            amountTxtField.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }
        return emptyValidationStatus;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTxtField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
